spring:
  profiles:
    active:
    - no-pattern-profile
#---
#spring:
#  profiles: dev
#  application: 
#    name: microconfig-test-dev
#---
#spring:
#  profiles: default
#  application: 
#    name: microconfig-test-default
